Home details and report
GeriLife/wellbeing-client pull request #6
Opened 2020-10-26 19:01 UTC by shailee-m

Adding details and report page for each home.

2020-10-31 10:34 UTC, brylie requested changes

2020-10-31 10:34 UTC, brylie commented on frontend/src/features/home-details/services/detail-services.js
> +};
Just for clarity of organization, could we please move the chart rendering functions into a different module? E.g. `features/home-details/charts/charts.js`? That way, the current file would deal *only* with data fetching, while the `charts.js` file would deal only with chart rendering. Kind of like separating forks and knives.

2020-10-31 10:34 UTC, brylie commented on frontend/src/features/home-details/services/detail-services.js
> +  Plotly.newPlot("homeActivityCountsByFacilitatorRoleChart", data, layout, {
I think the DOM element selector should be passed in as an argument to the render function. That way, it is apparent in the HTML template file which element is responsible for containing the chart. Then if the HTML element is changed, it is just a matter of changing an argument to the chart render function in the same file, as opposed to having to locate this line of code in a separate file.

2020-10-31 10:48 UTC, brylie requested changes
Make sure to run automatic code formatting on the Vue template files. I recommend using the Vetur VS Code plugin, as part of this extension pack:

https://marketplace.visualstudio.com/items?itemName=sdras.vue-vscode-extensionpack

2020-10-31 11:10 UTC, brylie commented
When rendering an individual Home page, The following error appears in a toast message:

```
TypeError: d3.nest is not a function<br> &nbsp; &nbsp;at Object.getHomeActivityTypeMetrics (server/methods/charts/homeCharts.js:125:15)<br> &nbsp; &nbsp;at packages/simple_rest.js:383:33<br> &nbsp; &nbsp;at packages/simple_json-routes.js:98:9
```

2020-10-31 11:11 UTC, brylie requested changes
We need to include `package-lock.json` in our repository.

2020-11-02 17:07 UTC, shailee-m commented
> We need to include `package-lock.json` in our repository.

the project was setup with yarn by default. yarn.lock is committed. Should I remove yarn?

2020-11-02 17:10 UTC, shailee-m commented
> ```
> TypeError: d3.nest is not a function<br> &nbsp; &nbsp;at Object.getHomeActivityTypeMetrics (server/methods/charts/homeCharts.js:125:15)<br> &nbsp; &nbsp;at packages/simple_rest.js:383:33<br> &nbsp; &nbsp;at packages/simple_json-routes.js:98:9
> ```

I think the yarn.lock has the exact d3 version. 
Can your reinstall the node_modules using the command `yarn` and check?

2020-11-03 20:13 UTC, brylie commented
Oops. I forgot we are using Yarn here. My bad.

2020-11-15 16:32 UTC, brylie approved these changes

2020-11-15 16:32 UTC, merged